config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.logout '/logout', :controller => 'sessions', :action => 'destroy'
  map.login '/login', :controller => 'sessions', :action => 'new'
  map.register '/register', :controller => 'users', :action => 'create'
  map.signup '/signup', :controller => 'users', :action => 'new'
  map.setting '/account/setting', :controller => 'users', :action => 'edit'

  map.resources :users do |user|
    user.resources :groups, :controller => 'user_groups', :member => {:join => :get}
  end

  map.resources :groups, :member => {:freeze => :post, :alive => :post, :freeze_date => :post, :report =>:get} do |group|
    group.resources :users, :controller => 'group_users', :member => {:approve => :get}, :collection => {:invite => :get}
    group.resources :expenses, :controller => "group_expenses", :collection => {:users_report => :get, :tabs_report => :get}
    group.resources :tags, :controller => "group_tags"
  end

  map.resources :tags

  map.resources :expenses

  map.resource :session
  
  map.resources :welcome, :collection => {:joined_groups => :get, :managed => :get, :my => :get}

  map.root :controller => 'welcome'

  #map.connect ':controller/:action/:id'
  #map.connect ':controller/:action/:id.:format'
end

app/models/group.rb
require 'digest/sha1'
class Group < ActiveRecord::Base
  has_many :user_group_relations
  has_many :users, :through => :user_group_relations
  has_many :tag_group_relations
  has_many :tags, :through => :tag_group_relations
  has_many :expenses

  STATE=["alive", "frozen"] 

  validates_presence_of :name, :short_name
  validates_length_of :name, :within => 3..40
  validates_length_of :short_name, :within => 3..40
  validates_format_of :url, :with => /^(http|https|ftp):\/\/.*/, :if => Proc.new { |group| !group.url.blank? }

  before_create :set_secret_id

  named_scope :approved_groups, :include=> :user_group_relations, :conditions => ["user_group_relations.approved = ?", true], :order => "groups.created_at DESC"
  named_scope :unapprove_groups, :include => :user_group_relations, :conditions => ["user_group_relations.approved = ?", false], :order => "groups.created_at DESC"
  named_scope :managed_groups, :include => :user_group_relations, :conditions => ["user_group_relations.manager = ?", true], :order => "groups.created_at DESC"
  named_scope :alive, :conditions => "state = 'alive'"

  def to_param
    self.secret_id
  end

  # Get group users
  def managers
    self.users.managers
  end

  def approved_users_but_not_manager
    self.users.approved_users - self.users.managers
  end

  def approved_users
    self.users.approved_users
  end

  def unapprove_users
    self.users.unapprove_users
  end

  #Add user or remove a joined user 
  def add_manager(user)
    unless self.users.include?(user)
      ugr = self.user_group_relations.new(:user_id => user.id)
    else
      ugr = self.user_group_relations.find_by_user_id(user.id)
    end
    ugr.approved = true
    ugr.manager = true
    ugr.save
  end

  def add_approved_user(user)
    unless self.users.include?(user)
      ugr = self.user_group_relations.new(:user_id => user.id)
    else
      ugr = self.user_group_relations.find_by_user_id(user.id)
    end
    ugr.approved = true
    ugr.save
  end 

  def add_unapprove_user(user)
    self.user_group_relations.create(:user_id => user.id) unless self.user_group_relations.find_by_user_id(user.id)
  end

  def remove_joined_user(user)
    ugr = self.user_group_relations.find_by_user_id(user.id)
    ugr.destroy if ugr
  end

  # get report
  
  def users_report(start_date = Date.parse("2009-01-01"), end_date = Date.today)
    self.approved_users.map do |user|
      [user.login, user.expenses.by_group(self).during(start_date, end_date).total]
    end
  end

  def tags_report(start_date = Date.parse("2009-01-01"), end_date = Date.today)
    self.tags.map do |tag|
      [tag.name, self.expenses.by_tag(tag).during(start_date, end_date).total]
    end
  end

  #for state
  
  def set_freeze
    update_attribute(:state, "frozen")
  end
  
  def set_alive
    update_attribute(:state, "alive")
  end

  def frozen?
    return true if self.state == 'frozen'

    false
  end

  def alive?
    return true if self.state == 'alive'

    false
  end

  private

  def set_secret_id
    self.secret_id = Digest::SHA1.hexdigest(Time.now.to_f.to_s)
  end
end

# == Schema Information
#
# Table name: groups
#
#  id                :integer         not null, primary key
#  name              :string(255)
#  short_name        :string(255)
#  secret_id         :string(255)
#  owner_id          :integer
#  created_at        :datetime
#  updated_at        :datetime
#  state             :string(255)     default("alive")
#  froze_before_date :date
#  url               :string(255)
#  description       :text
#

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :login_required
  before_filter :get_group, :except => [:index, :new, :create]
  before_filter :group_manager_required, :only=>[:edit, :update, :destroy, :freeze, :alive, :freeze_date]

  def index
    @groups = @current_user.groups 

    respond_to do |format|
      format.html 
    end
  end

  def show
    respond_to do |format|
      format.html do
        @start_date = Date.parse(params[:start_date]) rescue  (Date.today - 1.month)
        @end_date = Date.parse(params[:end_date]) rescue Date.today
      end
      format.mobile do
        @expenses = @group.expenses.find(:all, :limit => 5, :order => "id DESC", :conditions => ["user_id = ?", @current_user.id])
      end
    end
  end

  def new
    @group = Group.new
    store_location

    respond_to do |format|
      format.html
    end
  end

  def edit
    store_location
  end

  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        @group.add_manager(@current_user)
        notice_stickie t("group.create_successfully")
        format.html { redirect_to(@group) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update

    respond_to do |format|
      if @group.update_attributes(params[:group])
        notice_stickie t("group.update_successfully")
        format.html { redirect_to(@group) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to(groups_url) }
    end
  end

  def freeze
    @group.set_freeze
    notice_stickie t('group.frozen_message')
    redirect_to(@group)
  end

  def alive
    @group.set_alive
    redirect_to(@group)
  end

  def freeze_date
    fd = Date.parse(params[:froze_before_date]) unless params[:froze_before_date].blank?
    @group.update_attribute(:froze_before_date, fd)
    redirect_to(@group)
  end

  def report
    @start_date = Date.parse(params[:start_date]) rescue Date.today - 1.month 
    @end_date = Date.parse(params[:end_date]) rescue Date.today

    respond_to do |format|
      format.mobile
    end
  end

  private

  def get_group
    @group = Group.find_by_secret_id(params[:id])
    unless @group
      no_right_to_access
      return false
    end
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
  def group_state_message(group)

    return t("group.frozen_message") if group.state == 'frozen'

    return t("group.frozen_before_date", :frozen_date => group.froze_before_date) if group.froze_before_date

    return ""
  end
end

app/views/groups/_form.html.erb
<%= f.error_messages %>
<%= f.text_field :name, :label => Group.human_attribute_name(:name) %>
<%= f.text_field :short_name, :label => Group.human_attribute_name(:short_name) %>
<br />
<h3><%= t("group.select_tag", :url => new_tag_path) %></h3>
<%= f.many_check_boxes("tag_ids", Tag.outgoing.map{|tag| [tag.name, tag.id]}, :label => t("group.outgoing_tag")) %>

<%= f.text_field :url, :label => Group.human_attribute_name(:url) %>

app/views/groups/_item.html.erb
<tr id = '<%= "user_report_#{name}" %>'>
  <td><%=h name %></td>
  <td class = 'amount'><%= number_to_currency(total, :precision => 0, :unit => "") %></td>
</tr>

app/views/groups/_list.html.erb
<table class ='table'>
  <tr>
    <th><%=h Expense.human_attribute_name("user") %></th>
    <th><%=h Expense.human_attribute_name("amount") %></th>
    <th><%=h Expense.human_attribute_name("entry_date") %></th>
  </tr>
  <% expenses.each do |expense| -%>
    <tr>
      <td><%= expense.user.to_brief_info %></td>
      <td class='money'><%= show_amount(expense) %></td>
      <td><%= expense.entry_date %></td>
    </tr>
  <% end -%>
</table>

app/views/groups/_menu.html.erb
<div id='submenu'>
<%= render_list :class => 'menu' do |list|
  list << link_to(t("group.joined_users"), group_users_path(@group)) if @current_user.manager?(@group)
  list << link_to(t("group.requiest_to_join"), join_user_group_path(@current_user, @group)) if @current_user.not_join?(@group)
  list << link_to("邀請", new_group_user_path(@group)) if @current_user.manager?(@group)
  list << link_to(t("group.quit"), user_group_path(@current_user,@group), :method => :delete, :confirm => t("group.quit_confirm")) if !@current_user.manager?(@group) && @current_user.join?(@group)
  list << link_to(t("group.all_expenses"), group_expenses_path(@group)) if @current_user.approved?(@group)
  list << link_to(t("group.add_outgoing_expense"), new_group_expense_path(@group, :kind => :outgoing)) if @current_user.approved?(@group) && @group.alive?
  #list << link_to(t("group.add_income_expense"), new_group_expense_path(@group, :kind => :income)) if @current_user.approved?(@group)
  list << link_to(t("edit"), edit_group_path(@group)) if @current_user.manager?(@group)
  list << link_to(t("group.freeze"), freeze_group_path(@group), {:method => :post}) if @current_user.manager?(@group) && @group.state != "frozen"
  list << link_to(t("group.alive"), alive_group_path(@group), {:method => :post}) if @current_user.manager?(@group) && @group.state == "frozen"
  list << "<a id='freeze_date_link' href='#'>#{Group.human_attribute_name(:froze_before_date)}</a>" if @current_user.manager?(@group)
end -%>
</div>

<div id="froze_before_date_div" style="display:none;">
  <% form_tag freeze_date_group_path(@group), :class=>'form' do -%>
    <div style='margin-left:10px;'>
      <%= text_field_tag :froze_before_date, @group.froze_before_date, :size => 12, :style=>'float:left;' %>
      <%= submit_tag t("ok"), :style => "margin-left: 10px;" %>
    </div>
<% end -%>
</div>

app/views/groups/_total.html.erb
<tr class='total'>
  <td><%=h Group.human_attribute_name("total") %></td> 
  <td class = 'amount'><%=h number_to_currency(total, :precision => 0, :unit => "") %></td> 
</tr>

app/views/groups/edit.html.erb
<div class="block">
  <div class="content clearfix">
    <h2><%=h t("group.edit") %></h2>
    <div class="inner">
      <% handicraft_form_for(@group,:html =>{:class => :form}) do |f| %>
         <%= render :partial => 'form', :locals => {:f =>f}  %>
        <div class="group navform">
          <%= f.submit t("update") %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="block">
  <div class="content clearfix">
    <h2><%= t("group.my_groups") %></h2>
    <div class="inner grid_10 alpha">
      <% unless @groups.empty? -%>
        <table class ='table'>
          <tr>
            <th><%= Group.human_attribute_name(:name) %></th>
            <th><%= Group.human_attribute_name(:short_name) %></th>
            <th></th>
          </tr>

          <% @groups.each do |group| %>
            <tr>
              <td><%=h group.name %></td>
              <td><%=h group.short_name %></td>
              <td>
                <%= render_list :class => 'menu' do |list|
                  list << link_to(t(:show), group)
                  list << link_to(t(:edit), edit_group_path(group)) if @current_user.manager?(group) 
                  list << link_to(t(:destroy), group, :confirm => t(:are_you_sure_to_destroy), :method => :delete) if @current_user.manager?(group) 
                end -%>
              </td>
            </tr>
          <% end %>
        </table>

      <% else -%>
        <div>
          <p><%= t("group.no_group_message") %></p>
          <p><%= link_to t("group.add_group"), new_group_path %></p>
        </div>
      <% end -%>

    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="block">
  <div class="content clearfix">
    <h2><%= t('group.new') -%></h2>
    <div class="inner">
      <% handicraft_form_for(@group, :html =>{:class => :form}) do |f| %>
        <%= render :partial => 'form', :locals => {:f =>f} %>
        <%= f.submit t('create') %>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/report.mobile.erb
<% content_for :header_link do -%>
  <%= link_to Group.human_name, group_path(@group), :class => "button back-button" %>
  <%= link_to "新增", new_group_expense_path(@group), :class => "button next-button" %>
<% end -%>

<% content_for :select_date do -%>
  <% form_for report_group_path(@group), :html => {:method => :get} do -%>
    <div id="date">
    <%= text_field_tag :start_date, @start_date.to_date, :class => 'text', :readonly => 'true' %>
    <span>TO</span>
    <%= text_field_tag :end_date, @end_date.to_date, :class => 'text', :readonly => 'true' %>
    <%= submit_tag "確定", :style => "float: right;" %>
  </div>
  <% end -%>
  
<% end -%>

<div id='tabs' class="section account">
  <ul>
    <li><%= link_to "團友", users_report_group_expenses_path(@group, :start_date => @start_date, :end_date => @end_date) %></li>
    <li<%= link_to "分類", tabs_report_group_expenses_path(@group, :start_date => @start_date, :end_date => @end_date) %></li>
  </ul>
</div>

<% content_for :page_specific_javascript do -%>
  <script type="text/javascript">
    var option = {dateFormat: 'yy-mm-dd'};
    $(function(){
        $('#start_date').datepicker(option);
        $('#end_date').datepicker(option);

        $("#tabs").tabs({
          ajaxOptions: {
            error: function(xhr, status, index, anchor) {
              $(anchor.hash).html("Couldn't load this tab. We'll try to fix this as soon as possible.");
            }
          }
        });
    });
  </script>
<% end -%>

app/views/groups/show.html.erb
<div class="block">
  <div class="content clearfix">
    <h2><%= t("group.show", :group => @group.name) %><label style="margin-left:20px;"> <%= group_state_message(@group) %></label></h2>
    <div class="inner grid_10 alpha">
      <%= render :partial => 'menu'  %>
      <br /><br />
      <p><%=h Group.human_attribute_name("name") %>: <%=h @group.name %></p>
      <p><%=h Group.human_attribute_name("short_name") %>: <%=h @group.short_name %></p>
      <% if @current_user.approved?(@group) -%>
        <p><%=h Group.human_attribute_name("total") %>: <%=h number_to_currency(@group.expenses.total, :precision => 0) %> </p>
        <br />
        <div class="inner grid_10 alpha">
          <% form_for :expense, :url => group_path(@group), :html => {:method => :get} do |f| %>
            <label>Start Date: </label><%= text_field_tag :start_date, @start_date.to_s(:db), :id=>'start-date' -%>
            <label>End Date: </label><%= text_field_tag :end_date, @end_date.to_s(:db), :id => 'end-date' -%>
            <%= f.submit "Search" %>
          <% end -%>
        </div>
        <br /><br />
        <div id='tabs'>
          <ul>
            <li><%= link_to t("expenses.user_report"), users_report_group_expenses_path(@group, :start_date => @start_date, :end_date => @end_date) %></li>
            <li><%= link_to t("expenses.tag_report"), tabs_report_group_expenses_path(@group, :start_date => @start_date, :end_date => @end_date) %></li>
          </ul>
        </div>
      <% end -%>
    </div>
  </div>
</div>
<% content_for :page_specific_javascript do-%>
  <script type="text/javascript">
    var option = {dateFormat: 'yy-mm-dd'};
    $(function(){
      $("a","#submenu").button();

      $("#tabs").tabs({
          ajaxOptions: {
            error: function(xhr, status, index, anchor) {
              $(anchor.hash).html("Couldn't load this tab. We'll try to fix this as soon as possible.");
            }
          }
          });

      $('#start-date').datepicker(option);
      $('#end-date').datepicker(option);

      if($('#freeze_date_link').length != 0){
        var freeze_date_link_pos = $('#freeze_date_link').position();
        $('#froze_before_date_div').css({top: freeze_date_link_pos.top + 8, 
                                     left: freeze_date_link_pos.left + 110}); 
        $('#freeze_date_link').click(function(){
          $('#froze_before_date_div').toggle();
          });
        $('#froze_before_date').datepicker(option);
      }
        
    });
</script>
<% end -%>

app/views/groups/show.mobile.erb
<% content_for :header_link do -%>
  <a href="/" class="button back-button">首頁</a>
  <%= link_to "報表", report_group_path(@group), :class=>"button logout" %>
<% end -%>

<div id="container">
  <h3><%=h @group.name %></h3>
  <label style='font-size: 12px;'> <%= group_state_message(@group) %></label>
  <ul class="menu list">
    <li><%= link_to t("expenses.add_outgoing_expense"), new_group_expense_path(@group) %></li>
  </ul>

  <h3>快速報帳</h3>
  <ul class="menu list">
    <% @expenses.each do |expense| %>
      <li><%= link_to( truncate("#{expense.tag.name} / #{expense.amount.to_i} / #{expense.note}", 25), new_group_expense_path(@group, :template => expense.id)) %></li>
    <% end %> 
  </ul>

</div>